services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: parser-test_php
    working_dir: /var/www/parser-test/src
    volumes:
      - ./:/var/www/parser-test
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    container_name: parser-test_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: parser_test
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
