#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_REVIEWER_USER}'@'%' IDENTIFIED BY '${MYSQL_REVIEWER_PASSWORD}';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_REVIEWER_USER}'@'%';
FLUSH PRIVILEGES;
SQL
